[build]
  command = "npm run build"
  publish = "dist"

  # (opcional) si usas monorepo, aquí NO pongas nada porque tu base es la raíz
  # base = "/"

[build.environment]
  NODE_VERSION = "20"
  # Si tuvieras problemas con esbuild en CI:
  # CI = "false"
